language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script:  
  - cd src || exit 1
  - python -m test.test_hkdf
  - coverage run --source . -m test.test_hkdf
#after_success:
#  - coveralls
#env:
#  - TEST=test1
#  - TEST=test2

